/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.14.3/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    kotlin("jvm") version "1.9.10"
    id("org.jetbrains.compose") version "1.5.10"  // Compose plugin
    application
}

repositories {
    google()

    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Compose
    implementation(compose.desktop.currentOs)
    implementation("org.jetbrains.compose.ui:ui:1.5.10")
    implementation("org.jetbrains.compose.material:material:1.5.10")
    implementation("org.jetbrains.compose.foundation:foundation:1.5.10")

    // Ktor WebSocket client
    implementation("io.ktor:ktor-client-core:2.3.4")
    implementation("io.ktor:ktor-client-cio:2.3.4")
    implementation("io.ktor:ktor-client-websockets:2.3.4")
    implementation("io.ktor:ktor-websockets:2.3.4")

    // JUnit 5 for testing
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.10.0")
    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine:5.10.0")
}



// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    // Define the main class for the application.
    mainClass = "org.example.AppKt"

    // I don't know what this is for
    mainClass.set("MainKt")
}



java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(17))
    }
}